name: master_thesis_back_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - flask
      - flask-cors
      - fastapi
      - uvicorn
      - sqlalchemy
      - psycopg2-binary
      - pydantic
      - alembic
      - python-dotenv
      - httpx
      - pytest
      - pytest-asyncio
      - pytest-cov
      - coverage
      - pre-commit
      - pymongo
      - requests
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
